# Generated by Django 2.2 on 2020-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200812_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='likeCounter',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
