# Generated by Django 2.2 on 2020-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200812_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likeCounter',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
