# Generated by Django 2.2 on 2020-08-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likeCounter',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='likeCounter',
        ),
    ]
