# Generated by Django 2.2 on 2020-09-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='integer',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
