# Generated by Django 2.2 on 2020-09-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
