# Generated by Django 2.2 on 2020-09-27 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='integer',
        ),
    ]
