# Generated by Django 2.2 on 2020-09-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postlike_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='content',
        ),
    ]
